

const Employee = require("../models/Employee");
// const bcrypt = require("bcrypt");
const bcrypt = require('bcryptjs');
const jwt = require("jsonwebtoken");
const { Sequelize } = require("sequelize");
const errorHandlerMiddleware = require("../middleware/errorHandlerMiddleware");
const { createError, createSuccess } = require("../utils/errorMessages");

exports.getAllEmployees = async (req, res) => {
  try {
    const employees = await Employee.findAll(); // Retrieve all employees
    res.status(200).json(employees);
  } catch (error) {
    res.status(500).json({ message: "Error retrieving employees", error });
  }
};

exports.getEmployeeById = async (req, res) => {
  const { id } = req.params;
  try {
    const employee = await Employee.findOne({
      where: { desk_employee_id: id },
    });
    if (employee) {
      res.status(200).json(employee);
    } else {
      res.status(404).json({ message: "Employee not found" });
    }
  } catch (error) {
    res.status(500).json({ message: "Error retrieving employee", error });
  }
};

exports.createEmployee = async (req, res) => {
  try {
    const employeeData = req.body;
    if (!employeeData || !employeeData.desk_employee_id) {
      return res.json({ message: "desk_employee_id is missing", status: 0 });
    }

    // Check if the employee with the provided desk_employee_id already exists
    const existingEmployeeById = await Employee.findOne({
      where: { desk_employee_id: employeeData.desk_employee_id },
    });

    if (existingEmployeeById) {
      return res.json({
        message: "Employee with this desk_employee_id already exists",
        status: 0,
      });
    }

    // Check if the email is already in use by another employee
    const existingEmployeeByEmail = await Employee.findOne({
      where: { email: employeeData.email },
    });

    if (existingEmployeeByEmail) {
      return res.json({
        message: "Email is already in use by another employee",
        status: 0,
      });
    }

    // Create the new employee using the fields defined in the model
    const newEmployee = await Employee.create({
      desk_employee_id: employeeData.desk_employee_id,
      name: employeeData.name,
      email: employeeData.email,
      group_name: employeeData.group_name,
      profile_url: employeeData.profile_url,
      created_at: employeeData.created_at, // Optional, can be auto-generated by Sequelize
      updated_at: employeeData.updated_at, // Optional, can be auto-generated by Sequelize
    });

    return res.json({
      message: "Employee successfully created",
      status: 1,
      newEmployee,
    });
  } catch (error) {
    console.log(`Exception: ${error.message}`);
    return errorHandlerMiddleware(error, req, res);
  }
};


exports.updateEmployee = async (req, res) => {
  const { id } = req.params;
  const { name, email, group_name, profile_url } = req.body;

  try {
    if (!name || !email || !group_name) {
      return res.json({ message: "Required fields are missing", status: 0 });
    }

    const employee = await Employee.findOne({
      where: { desk_employee_id: id },
    });

    if (!employee) {
      return res.json({ message: "Employee not found", status: 0 });
    }

    const existingEmployee = await Employee.findOne({
      where: { email, desk_employee_id: { [Sequelize.Op.ne]: id } },
    });

    if (existingEmployee) {
      return res.json({
        message: "Email is already in use by another employee",
        status: 0,
      });
    }

    // Update the employee with the new values
    employee.name = name || employee.name;
    employee.email = email || employee.email;
    employee.group_name = group_name || employee.group_name;
    employee.profile_url = profile_url || employee.profile_url;

    await employee.save();

    res.json({
      message: "Employee updated successfully",
      status: 1,
      employee,
    });
  } catch (error) {
    console.log(`Exception: ${error.message}`);
    return errorHandlerMiddleware(error, req, res);
  }
};

exports.toggleEmployeeStatus = async (req, res) => {
  const { id } = req.params;
  try {
    const employee = await Employee.findOne({
      where: { desk_employee_id: id },
    });
    if (!employee) {
      return res.status(404).json({ message: "Employee not found" });
    }

    // Toggle status logic, if needed (but the model has no status field anymore)
    res.status(200).json({ message: "Employee status change logic needs to be defined" });
  } catch (error) {
    res.status(500).json({ message: "Error toggling employee status", error });
  }
};

exports.deleteEmployee = async (req, res) => {
  const { id } = req.params;
  try {
    const employee = await Employee.findOne({
      where: { desk_employee_id: id },
    });

    if (!employee) {
      return res.status(404).json({ message: "Employee not found" });
    }

    // Deleting employee logic: removing instead of a soft-delete with "status"
    await employee.destroy();
    res.status(200).json({ message: "Employee deleted successfully" });
  } catch (error) {
    res.status(500).json({ message: "Error deleting employee", error });
  }
};

exports.loginEmployee = async (req, res) => {
  try {
    const { email, password } = req.body;

    // Find employee by email
    const employee = await Employee.findOne({
      where: { email },
    });
    if (!employee) {
      return res.status(404).json({ error: "Employee not found." });
    }

    // If password matching is necessary, ensure password is hashed and exists in model
    const isPasswordValid = await bcrypt.compare(password, employee.password);
    if (!isPasswordValid) {
      return res.status(401).json({ error: "Invalid password." });
    }

    // Generate JWT (if needed for employee)
    const token = jwt.sign(
      { employeeId: employee.desk_employee_id, email: employee.email },
      process.env.JWT_SECRET,
      { expiresIn: "1d" }
    );

    res.json({ message: "Login successful", token, employeeData: employee });
  } catch (err) {
    console.error("Error logging in employee:", err);
    res.status(500).json({ error: "An error occurred during login." });
  }
};

